### ISSUE TITLE
cargo update -p evm fails

### ISSUE THREAD

**Issue by crystalin** [PureStake/moonbeam-runtime-overrides#49]
└--╼ cargo update -p evm
error: There are multiple `evm` packages in your project, and the specification `evm` is ambiguous.
Please re-run this command with `-p <spec>` where `<spec>` is one of the following:
  https://github.com/rust-lang/crates.io-index#evm:0.35.0
  https://github.com/rust-blockchain/evm#0.35.0

**Comment by librelois** [comment]
I had added it in the past because it was necessary to update the Cargo.lock on our evm patch. But now that we're not using a patch for evm, we just need to stop running this command.
